services:
  adminer:
    image: adminer
    ports:
      - 5431:8080
    # restart: always
  db:
    image: postgres:16.8
    environment:
      POSTGRES_DB: bts_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    # restart: always
    shm_size: 128mb
